name: Run Tests
on:
  [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [debian-10, ubuntu-18.04]
    steps:
      # checkout repository
      - uses: actions/checkout@v2
      # set up container
      - name: Setup miktex container
        uses: ./.github/actions/${{ matrix.container }}
      # install python
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      # install python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      # run tox
      - name: Run tox
        run: |
          tox
